{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "astro-data-workspace.fullname" . }}
  labels:
    {{- include "astro-data-workspace.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths: {{ toYaml .paths | nindent 10 }}
    {{- end }}
  {{- with .Values.ingress.tls }}
  tls: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
