{{- if and .Values.dataWarehouse.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "astro-data-workspace.serviceAccountName" . }}
  labels:
    {{- include "astro-data-workspace.labels" . | nindent 4 }}
{{- end }}
